---
- name: Converge
  hosts: all
  become: True
  roles:
    - role: systemli.mariadb
    - role: ansible-role-nextcloud
  vars:
    nextcloud_webserver: none
    nextcloud_admin_password: topsecret
    nextcloud_mysql_password: topsecret
    nextcloud_patches:
      - test-robots-txt.diff
    nextcloud_config:
      system:
        memcache.local: '\OC\Memcache\APCu'
        trusted_domains:
          - localhost
      apps:
        core:
          backgroundjobs_mode: cron
        dav:
          system_addressbook_exposed: "no"
